frontend/controllers/CatalogController.php
<?php

namespace frontend\controllers;

use backend\models\Categories;
use backend\models\CategoriesImages;
use backend\models\Ingredients;
use backend\models\IngredientCategories;

class CatalogController extends \yii\web\Controller
{
    public function actionView($pretty_url)
    {
        $model = new Categories();
        $currentCat = $model->findOne(['pretty_url' => $pretty_url]);
        $image_model = new CategoriesImages();
        $image = $image_model->findOne(['category_id' => $currentCat['id']]);
        return $this->render('view',
            [
                'category' => $currentCat,
                'image' => $image,
                'productList' => $currentCat->getProductsList(),
            ]);
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionCreatePizza()
    {
        $ingredient_cat_model = new IngredientCategories();
        $ingredientList = $ingredient_cat_model->getIngredientsList();

        if (\Yii::$app->request->isAjax)
        {
            var_dump($_POST);die;
        }
        return $this->render(
            'createPizza',
            [
                'model' => $ingredientList
            ]
            );
    }

}

frontend/views/catalog/createPizza.php
<?php
/**
 * Created by PhpStorm.
 * User: sebulba
 * Date: 02.03.16
 * Time: 4:01
 */
use frontend\components\CreateWidget;
use yii\helpers\Url;

$this->registerJsFile(
    '//code.jquery.com/ui/1.11.4/jquery-ui.js',
    ['depends'=>'frontend\assets\AppAsset']
);
$this->registerJsFile(
    '/js/createPizza.js',
    ['depends'=>'frontend\assets\AppAsset']
);
$this->registerCssFile(
    '//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css',
    ['depends'=>'frontend\assets\AppAsset']
);
$this->registerCssFile(
    '/css/createPizza.css',
    ['depends'=>'frontend\assets\AppAsset']
);
$this->title = 'Create Pizza';
$this->params['breadcrumbs'][] = ['label' => 'Catalog', 'url' => [Url::toRoute(['catalog/'])]];
$this->params['breadcrumbs'][] = $this->title;
 echo CreateWidget::widget(
     [
         'model' => $model
     ]
 );
?>
<div class="row ingredients-list-wrapper">
    <div class="col-sm-6 ingredients-list">
        <span class="ingredients-list-caption">
            Ваша піца включає:
        </span>
    </div>
</div>

frontend/views/catalog/index.php
<?php

use yii\helpers\Html;
use frontend\components\CatalogTileWidget;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel backend\models\CategoriesSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Catalog';
$this->registerCssFile("/css/CatalogTile.css");
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="categories-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <div class="row text-center">
        <?= html::a(
            html::img(
                'https://bcrc.bio.umass.edu/pedigreesoftware/sites/default/files/CREATE.jpg').
                    'Create Pizza',
                Url::toRoute(['catalog/create-pizza']))?>
    </div>
    <div class="row text-center">
        <?= CatalogTileWidget::widget([]); ?>
    </div>
</div>

frontend/views/catalog/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use frontend\components\CatalogChildWidget;
/* @var $this yii\web\View */
$this->title = $category->attributes['meta_title'];
$this->registerCssFile(
    "/css/CatalogChild.css",
    ['depends'=>'frontend\assets\AppAsset']
);
$this->registerJsFile(
    '/js/sendAjaxOrder.js',
    ['depends'=>'frontend\assets\AppAsset']
);
$this->params['breadcrumbs'][] = ['label' => 'Catalog', 'url' => [Url::toRoute(['catalog/'])]];
$this->params['breadcrumbs'][] = $this->title;
$attachedImage = $category->getImage();
?>
<div class="row">
    <div class="col-md-12"><h1><?=$category->attributes['meta_title']?></h1></div>
</div>
<div class="row">
    <div class="col-sm-7">
        <?=html::img(
            '/'.$attachedImage->getPath('200x'),
            [
                'alt' => $image->alt
            ]
        )?>
    </div>
    <div class="col-sm-5"><p><?=$category->attributes['description']?></p></div>
</div>
<div class="row">
    <?=CatalogChildWidget::widget([
        'productList' => $productList,
        'category' => $category
    ]); ?>
</div>